apiVersion: v1
kind: ServiceAccount
metadata:
  name: ace-tekton-service-account
  namespace: acereg
spec:
  securityContext:
  runAsUser: 1000
secrets:
  - name: bregcred
imagePullSecrets:
  - name: bregcred

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: acereg
  name: pipeline-role
rules:
- apiGroups: ["extensions", "apps", ""]
  resources: ["services", "deployments", "pods"]
  verbs: ["get", "create", "update", "patch", "list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-role
subjects:
- kind: ServiceAccount
  name: ace-tekton-service-account
  namespace: acereg
